---
- name: Create user
  hosts: test
  remote_user: root
  tasks:
    - name: Create new user
      user:
        name: user1
    - name: Create .ssh folder
      file:
        path: ~user1/.ssh
        state: directory
        owner: user1
        group: user1
        mode: 0700
    - name: Upload SSH key
      copy:
       src: ../../../home/ilia/.ssh/id_rsa
       dest: ~user1/.ssh/id_rsa
       owner: user1
       group: user1
       mode: 0700
