---
- name: Postfix
  hosts: test
  user: root

  tasks:
    - name: Set Postfix option hostname
      debconf: name=postifx question="postfix/mailname" value="{{ansible_fqdn}}" vtype="string"
      tags: instal_postfix

    - name: Set Postfix option type as internet site
      debconf: name=postfix question="postfix/main_mailer_type" value="'Internet Site'" vtype="string"
      tags: install_postfix

    - name: Install Postfix
      apt: package={{ item }} state=present
      with_items:
        - postfix
        - mailutils
      tags: install_postfix

    - name: Uninstall Postfix
      apt: package={{ item }} state=absent
      with_items:
        - postfix
        - mailutils
      tags: drop_postfix
